version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=construction_map
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-development}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - uploaded_files:/app/uploads
    depends_on:
      - db
    restart: unless-stopped
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
      
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=construction_map
    ports:
      - "5432:5432"
    restart: unless-stopped
    
volumes:
  postgres_data:
  uploaded_files: 