"""Save current database state

Revision ID: 04dd92bd5b45
Revises: ada64e77e7e6
Create Date: 2025-05-15 10:48:00.388630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04dd92bd5b45'
down_revision = 'ada64e77e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_id', table_name='metrics')
    op.drop_index('ix_metrics_name', table_name='metrics')
    op.drop_index('ix_metrics_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_column('event_comments', 'file_type')
    op.alter_column('event_history', 'additional_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_event_history_id'), 'event_history', ['id'], unique=False)
    op.create_foreign_key(None, 'event_history', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_history', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_constraint(None, 'event_history', type_='foreignkey')
    op.drop_constraint(None, 'event_history', type_='foreignkey')
    op.drop_index(op.f('ix_event_history_id'), table_name='event_history')
    op.alter_column('event_history', 'additional_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('event_comments', sa.Column('file_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metrics_pkey')
    )
    op.create_index('ix_metrics_timestamp', 'metrics', ['timestamp'], unique=False)
    op.create_index('ix_metrics_name', 'metrics', ['name'], unique=False)
    op.create_index('ix_metrics_id', 'metrics', ['id'], unique=False)
    # ### end Alembic commands ### 